### ISSUE TITLE
Component Diagram Implementation

### ISSUE THREAD

**Issue by alphonsekoh** [alphonsekoh/ICT2106-P2-05#3]
- [x] Creation of Lucid Chart
- [x] Group and Identify similar classes and interfaces in Class Diagram
- [x] Interface the components

**Comment by xcxpcxkes** [comment]
Update on 16/2/22

Minor edits on the component diagram to include UOW and generic repository

**Comment by alphonsekoh** [comment]
Components Diagram reviewed, might need some inputs from Prof Alex and Prof Serena.

**Comment by xcxpcxkes** [comment]
Update on 18/2/22

Include HospitalContext in the component diagram
