### ISSUE TITLE
How should Sprint 2 be conducted?

### ISSUE THREAD

**Issue by alphonsekoh** [alphonsekoh/ICT2106-P2-05#34]

**Comment by alphonsekoh** [comment]
- Revision of all the diagrams and consolidate Class, Components and Architecture Diagram from other teams and modules
- Improve in managing the team by getting to know more about their work concerns frequently

**Comment by AfnanMuhd** [comment]
- Ensuring that the classes in the class diagram matches with the codes.
- Improve the different diagram based on the feedback that was given in Sprint 1.
- Ensuring that certain goals are achieved within a specific timeframe.

**Comment by xcxpcxkes** [comment]
- Information from the other modules and teams to be aligned in documentation and codes
- Improvement on design document based on feedback given by professors and instructors
- Ensure that other teams are updated by any changes made in our team
- Ensure that our codes match according to what was designed

**Comment by NianKiat** [comment]
- Ensure the design of the diagram aligns with the coding and structure of the project
- standardize the layout design with the other team to show consistency

**Comment by Teruhii** [comment]
- Ensure that communication channels are maintained between the leaders, and between the leaders and their teams.
- Having a common document for standardisation of various requirements, plans, etc. So that all modules can be on the same page on architecture.
