### ISSUE TITLE
What did we learn in Sprint 1?

### ISSUE THREAD

**Issue by alphonsekoh** [alphonsekoh/ICT2106-P2-05#35]

**Comment by alphonsekoh** [comment]
- Layering techniques while building an architecture 
- What design patterns we could use while doing up the architecture with proper justification
- Proper communication between teams and modules are vital to ensure everyone are on the same page

**Comment by AfnanMuhd** [comment]
- Learn the importance of communicating between the team instead of passing information to different teams
- Ensuring that certain goals in the sprint has been achieved within the deadlines

**Comment by xcxpcxkes** [comment]
- Must have proper communication within team and modules to get all information on the same line
- Designing the architecture must be supported and aligned with what was taught through professors or Martin Fowler's books

**Comment by NianKiat** [comment]
- unit of work should display correctly instead and should should not be drawn in the component diagram in the as it is part of the asp net core

**Comment by Teruhii** [comment]
- We learnt that intra team and inter team communication is important to have all the members feel safe enough to work on the project sections individually.
- Constant communication with the relevant parties should be maintained to keep information up to date for easier clarification of requirements
