### ISSUE TITLE
What went wrong in Sprint 1?

### ISSUE THREAD

**Issue by alphonsekoh** [alphonsekoh/ICT2106-P2-05#36]

**Comment by alphonsekoh** [comment]
- Too many people are communicating across teams at the same time resulting in conflicting information that causes confusion at times. 
- Conflicting information that results in changes of design document at the final leg
- Lack of domain knowledge and technical knowledge resulted in the slowdown during the sprint

**Comment by xcxpcxkes** [comment]
- Miscommunication between modules resulting in duplicating and misinterpretation of information
- Team did not plan well for some tasks resulting in some last-minute work

**Comment by AfnanMuhd** [comment]
- The misinterpretation of some requirements have led to delay in some of the tasks in the sprint.
- There were some conflicting information between the different modules

**Comment by NianKiat** [comment]
- Misinterpretation of the unit of work 
- Wrong diagram flow drawn due to not understanding of the project well enough

**Comment by Teruhii** [comment]
- Misinterpretation of requirements of both the client and the project caused the team delays in determining the requirements needed.
- Misinterpretation with the implementation/architecture of the Unit of Work. Not realising the Unit of Work that we implemented is not exactly the unit of work of the EF Core
- Miscommunication between modules, leading to taking too much time to sort out the borders and coding workflow
