### ISSUE TITLE
What we did well in Sprint 1?

### ISSUE THREAD

**Issue by alphonsekoh** [alphonsekoh/ICT2106-P2-05#37]

**Comment by alphonsekoh** [comment]
- The team is proactive in Sprint 1 and knows who to seek help from (even asking help from other teams and classes)
- The team is communicative with one another and would help one another if the other needs help
- Team members proactively start on tasks to avoid time wastage, they know their work disseminated to them well.

**Comment by AfnanMuhd** [comment]
- The team is communicative and have regular meetings to update on the progress of each member.
- The workload is distributed evenly and every team member plays an important role for the different task.

**Comment by xcxpcxkes** [comment]
- Regular meetings to update on progress to communicate and keep each other updated
- Workload is clearly distributed and documented

**Comment by NianKiat** [comment]
- discussion and clarification with professor when in doubt
- tasked given were discussed and reedited to ensure correctness

**Comment by Teruhii** [comment]
- Team communication happens regularly in the common chat for all of the team's members to stay updated on what is happening.
- Team is not afraid to question and give feedback on each others' work for a better eventual product/code/document
