### ISSUE TITLE
Class Diagrams Revision

### ISSUE THREAD

**Issue by alphonsekoh** [alphonsekoh/ICT2106-P2-05#38]
- [x] Prof Review Comments 
- [x] Update Class Diagram
- [x] Class Diagram Revision

**Comment by xcxpcxkes** [comment]
Update on 9/3/22
- Modified class diagrams on accounts portion

**Comment by xcxpcxkes** [comment]
Update on 11/3/22
- Modified class diagram

**Comment by xcxpcxkes** [comment]
Update on 12/3/22
- Modified class diagrams to include DefaultQuestions

**Comment by xcxpcxkes** [comment]
Update on 15/3/22
- Modified class diagrams on accounts to include more fields in the entities table

**Comment by xcxpcxkes** [comment]
Update on 16/3/22
- Modified some of the tables in combined diagrams

**Comment by xcxpcxkes** [comment]
Update on 17/3/22
- Modified the diagrams after the feedback given back in lab

**Comment by xcxpcxkes** [comment]
Update on 7/4/22
- Update the class diagram with the other groups

**Comment by xcxpcxkes** [comment]
Update on 9/4/22 with the group
- Modified class diagram
- Added to report
