### ISSUE TITLE
Component Diagram Revision

### ISSUE THREAD

**Issue by alphonsekoh** [alphonsekoh/ICT2106-P2-05#39]
- [x] Prof Review Comments
- [x] Component Diagram Implementation

**Comment by xcxpcxkes** [comment]
Update on 12/3/22
- Discussed with the team to include another component for DefaultQuestions

**Comment by alphonsekoh** [comment]
Update on 14/3/22
- Revised Component diagram added with required components.

**Comment by xcxpcxkes** [comment]
Update on 17/3/22
- Modified the diagrams after the feedback given back in lab

**Comment by xcxpcxkes** [comment]
Update on 6/4/22 
- Update component diagram based on codes with @AfnanMuhd

**Comment by xcxpcxkes** [comment]
Update on 7/4/22
- Updated component diagram based on the other groups

**Comment by xcxpcxkes** [comment]
Issue closed cause it was edited with the group and submitted in the report
