### ISSUE TITLE
Viewing of user profile feature

### ISSUE THREAD

**Issue by xcxpcxkes** [alphonsekoh/ICT2106-P2-05#6]
16/3/22:
-Updated the admin services
-Create profile controller that contain method to view admin profile
-Create admin and practitioner view model
-Created the layout for view profile of admin and practitioner

17/3/22:
-Use switch case to identify if user role is administrator or practitioner
-Redirect view to view model in admin areas

24/3/22:
-ClaimType use to retrieve user id and role.

6/4/22: 
-Implement builder pattern and model binding for the admin portion
-Change from admin view model to admin model

**Comment by AfnanMuhd** [comment]
10/3/22
-Added feature to retrieve dummy data from database
-Created the view profile page
